#include "properties.hpp"

namespace pyorbbecsdk {
void define_properties(const py::object& m) {
  py::enum_<OBPropertyID>(m, "OBPropertyID")
      .value("OB_PROP_LDP_BOOL", OBPropertyID::OB_PROP_LDP_BOOL, "LDP switch")
      .value("OB_PROP_LASER_BOOL", OBPropertyID::OB_PROP_LASER_BOOL,
             "Laser switch")
      .value("OB_PROP_LASER_PULSE_WIDTH_INT",
             OBPropertyID::OB_PROP_LASER_PULSE_WIDTH_INT,
             "Read and write laser Time value")
      .value("OB_PROP_LASER_CURRENT_FLOAT",
             OBPropertyID::OB_PROP_LASER_CURRENT_FLOAT)
      .value("OB_PROP_FLOOD_BOOL", OBPropertyID::OB_PROP_FLOOD_BOOL)
      .value("OB_PROP_FLOOD_LEVEL_INT", OBPropertyID::OB_PROP_FLOOD_LEVEL_INT)
      .value("OB_PROP_DEPTH_MIRROR_BOOL",
             OBPropertyID::OB_PROP_DEPTH_MIRROR_BOOL)
      .value("OB_PROP_DEPTH_FLIP_BOOL", OBPropertyID::OB_PROP_DEPTH_FLIP_BOOL)
      .value("OB_PROP_DEPTH_POSTFILTER_BOOL",
             OBPropertyID::OB_PROP_DEPTH_POSTFILTER_BOOL)
      .value("OB_PROP_DEPTH_HOLEFILTER_BOOL",
             OBPropertyID::OB_PROP_DEPTH_HOLEFILTER_BOOL)
      .value("OB_PROP_IR_MIRROR_BOOL", OBPropertyID::OB_PROP_IR_MIRROR_BOOL)
      .value("OB_PROP_IR_FLIP_BOOL", OBPropertyID::OB_PROP_IR_FLIP_BOOL)
      .value("OB_PROP_MIN_DEPTH_INT", OBPropertyID::OB_PROP_MIN_DEPTH_INT)
      .value("OB_PROP_MAX_DEPTH_INT", OBPropertyID::OB_PROP_MAX_DEPTH_INT)
      .value("OB_PROP_DEPTH_SOFT_FILTER_BOOL",
             OBPropertyID::OB_PROP_DEPTH_SOFT_FILTER_BOOL)
      .value("OB_PROP_LDP_STATUS_BOOL", OBPropertyID::OB_PROP_LDP_STATUS_BOOL)
      .value("OB_PROP_DEPTH_MAX_DIFF_INT",
             OBPropertyID::OB_PROP_DEPTH_MAX_DIFF_INT)
      .value("OB_PROP_DEPTH_MAX_SPECKLE_SIZE_INT",
             OBPropertyID::OB_PROP_DEPTH_MAX_SPECKLE_SIZE_INT)
      .value("OB_PROP_DEPTH_ALIGN_HARDWARE_BOOL",
             OBPropertyID::OB_PROP_DEPTH_ALIGN_HARDWARE_BOOL)
      .value("OB_PROP_TIMESTAMP_OFFSET_INT",
             OBPropertyID::OB_PROP_TIMESTAMP_OFFSET_INT)
      .value("OB_PROP_HARDWARE_DISTORTION_SWITCH_BOOL",
             OBPropertyID::OB_PROP_HARDWARE_DISTORTION_SWITCH_BOOL)
      .value("OB_PROP_FAN_WORK_MODE_INT",
             OBPropertyID::OB_PROP_FAN_WORK_MODE_INT)
      .value("OB_PROP_DEPTH_ALIGN_HARDWARE_MODE_INT",
             OBPropertyID::OB_PROP_DEPTH_ALIGN_HARDWARE_MODE_INT)
      .value("OB_PROP_ANTI_COLLUSION_ACTIVATION_STATUS_BOOL",
             OBPropertyID::OB_PROP_ANTI_COLLUSION_ACTIVATION_STATUS_BOOL)
      .value("OB_PROP_DEPTH_PRECISION_LEVEL_INT",
             OBPropertyID::OB_PROP_DEPTH_PRECISION_LEVEL_INT)
      .value("OB_PROP_TOF_FILTER_RANGE_INT",
             OBPropertyID::OB_PROP_TOF_FILTER_RANGE_INT)
      .value("OB_PROP_LASER_MODE_INT", OBPropertyID::OB_PROP_LASER_MODE_INT)
      .value("OB_PROP_RECTIFY2_BOOL", OBPropertyID::OB_PROP_RECTIFY2_BOOL)
      .value("OB_PROP_COLOR_MIRROR_BOOL",
             OBPropertyID::OB_PROP_COLOR_MIRROR_BOOL)
      .value("OB_PROP_COLOR_FLIP_BOOL", OBPropertyID::OB_PROP_COLOR_FLIP_BOOL)
      .value("OB_PROP_INDICATOR_LIGHT_BOOL",
             OBPropertyID::OB_PROP_INDICATOR_LIGHT_BOOL)
      .value("OB_PROP_DISPARITY_TO_DEPTH_BOOL",
             OBPropertyID::OB_PROP_DISPARITY_TO_DEPTH_BOOL)
      .value("OB_PROP_BRT_BOOL", OBPropertyID::OB_PROP_BRT_BOOL)
      .value("OB_PROP_WATCHDOG_BOOL", OBPropertyID::OB_PROP_WATCHDOG_BOOL)
      .value("OB_PROP_HEARTBEAT_BOOL", OBPropertyID::OB_PROP_HEARTBEAT_BOOL)
      .value("OB_PROP_DEPTH_CROPPING_MODE_INT",
             OBPropertyID::OB_PROP_DEPTH_CROPPING_MODE_INT)
      .value("OB_PROP_D2C_PREPROCESS_BOOL",
             OBPropertyID::OB_PROP_D2C_PREPROCESS_BOOL)
      .value("OB_PROP_RGB_CUSTOM_CROP_BOOL",
             OBPropertyID::OB_PROP_RGB_CUSTOM_CROP_BOOL)
      .value("OB_PROP_DEVICE_WORK_MODE_INT",
             OBPropertyID::OB_PROP_DEVICE_WORK_MODE_INT)
      .value("OB_PROP_DEVICE_COMMUNICATION_TYPE_INT",
             OBPropertyID::OB_PROP_DEVICE_COMMUNICATION_TYPE_INT)
      .value("OB_PROP_LASER_ENERGY_LEVEL_INT",
             OBPropertyID::OB_PROP_LASER_ENERGY_LEVEL_INT)
      .value("OB_PROP_LDP_MEASURE_DISTANCE_INT",
             OBPropertyID::OB_PROP_LDP_MEASURE_DISTANCE_INT)
      .value("OB_PROP_TIMER_RESET_SIGNAL_BOOL",
             OBPropertyID::OB_PROP_TIMER_RESET_SIGNAL_BOOL)
      .value("OB_PROP_TIMER_RESET_TRIGGER_OUT_ENABLE_BOOL",
             OBPropertyID::OB_PROP_TIMER_RESET_TRIGGLE_OUT_ENABLE_BOOL)
      .value("OB_PROP_TIMER_RESET_DELAY_US_INT",
             OBPropertyID::OB_PROP_TIMER_RESET_DELAY_US_INT)
      .value("OB_PROP_CAPTURE_IMAGE_SIGNAL_BOOL",
             OBPropertyID::OB_PROP_CAPTURE_IMAGE_SIGNAL_BOOL)
      .value("OB_PROP_IR_RIGHT_MIRROR_BOOL",
             OBPropertyID::OB_PROP_IR_RIGHT_MIRROR_BOOL)
      .value("OB_PROP_CAPTURE_IMAGE_FRAME_NUMBER_INT",
             OBPropertyID::OB_PROP_CAPTURE_IMAGE_FRAME_NUMBER_INT)
      .value("OB_PROP_IR_RIGHT_FLIP_BOOL",
             OBPropertyID::OB_PROP_IR_RIGHT_FLIP_BOOL)
      .value("OB_PROP_COLOR_ROTATE_INT", OBPropertyID::OB_PROP_COLOR_ROTATE_INT)
      .value("OB_PROP_IR_ROTATE_INT", OBPropertyID::OB_PROP_IR_ROTATE_INT)
      .value("OB_PROP_IR_RIGHT_ROTATE_INT",
             OBPropertyID::OB_PROP_IR_RIGHT_ROTATE_INT)
      .value("OB_PROP_DEPTH_ROTATE_INT", OBPropertyID::OB_PROP_DEPTH_ROTATE_INT)
      .value("OB_PROP_LASER_HW_ENERGY_LEVEL_INT",
             OBPropertyID::OB_PROP_LASER_HW_ENERGY_LEVEL_INT)
      .value("OB_PROP_USB_POWER_STATE_INT",
             OBPropertyID::OB_PROP_USB_POWER_STATE_INT)
      .value("OB_PROP_DC_POWER_STATE_INT",
             OBPropertyID::OB_PROP_DC_POWER_STATE_INT)
      .value("OB_STRUCT_BASELINE_CALIBRATION_PARAM",
             OBPropertyID::OB_STRUCT_BASELINE_CALIBRATION_PARAM)
      .value("OB_STRUCT_DEVICE_TEMPERATURE",
             OBPropertyID::OB_STRUCT_DEVICE_TEMPERATURE)
      .value("OB_STRUCT_TOF_EXPOSURE_THRESHOLD_CONTROL",
             OBPropertyID::OB_STRUCT_TOF_EXPOSURE_THRESHOLD_CONTROL)
      .value("OB_STRUCT_DEVICE_SERIAL_NUMBER",
             OBPropertyID::OB_STRUCT_DEVICE_SERIAL_NUMBER)
      .value("OB_STRUCT_DEVICE_TIME", OBPropertyID::OB_STRUCT_DEVICE_TIME)
      .value("OB_STRUCT_MULTI_DEVICE_SYNC_CONFIG",
             OBPropertyID::OB_STRUCT_MULTI_DEVICE_SYNC_CONFIG)
      .value("OB_STRUCT_RGB_CROP_ROI", OBPropertyID::OB_STRUCT_RGB_CROP_ROI)
      .value("OB_STRUCT_DEVICE_IP_ADDR_CONFIG",
             OBPropertyID::OB_STRUCT_DEVICE_IP_ADDR_CONFIG)
      .value("OB_STRUCT_CURRENT_DEPTH_ALG_MODE",
             OBPropertyID::OB_STRUCT_CURRENT_DEPTH_ALG_MODE)
      .value("OB_STRUCT_DEPTH_PRECISION_SUPPORT_LIST",
             OBPropertyID::OB_STRUCT_DEPTH_PRECISION_SUPPORT_LIST)
      .value("OB_PROP_COLOR_AUTO_EXPOSURE_BOOL",
             OBPropertyID::OB_PROP_COLOR_AUTO_EXPOSURE_BOOL)
      .value("OB_PROP_COLOR_EXPOSURE_INT",
             OBPropertyID::OB_PROP_COLOR_EXPOSURE_INT)
      .value("OB_PROP_COLOR_GAIN_INT", OBPropertyID::OB_PROP_COLOR_GAIN_INT)
      .value("OB_PROP_COLOR_AUTO_WHITE_BALANCE_BOOL",
             OBPropertyID::OB_PROP_COLOR_AUTO_WHITE_BALANCE_BOOL)
      .value("OB_PROP_COLOR_WHITE_BALANCE_INT",
             OBPropertyID::OB_PROP_COLOR_WHITE_BALANCE_INT)
      .value("OB_PROP_COLOR_BRIGHTNESS_INT",
             OBPropertyID::OB_PROP_COLOR_BRIGHTNESS_INT)
      .value("OB_PROP_COLOR_SHARPNESS_INT",
             OBPropertyID::OB_PROP_COLOR_SHARPNESS_INT)
      .value("OB_PROP_COLOR_SATURATION_INT",
             OBPropertyID::OB_PROP_COLOR_SATURATION_INT)
      .value("OB_PROP_COLOR_CONTRAST_INT",
             OBPropertyID::OB_PROP_COLOR_CONTRAST_INT)
      .value("OB_PROP_COLOR_ROLL_INT", OBPropertyID::OB_PROP_COLOR_ROLL_INT)
      .value("OB_PROP_COLOR_AUTO_EXPOSURE_PRIORITY_INT",
             OBPropertyID::OB_PROP_COLOR_AUTO_EXPOSURE_PRIORITY_INT)
      .value("OB_PROP_COLOR_BACKLIGHT_COMPENSATION_INT",
             OBPropertyID::OB_PROP_COLOR_BACKLIGHT_COMPENSATION_INT)
      .value("OB_PROP_COLOR_HUE_INT", OBPropertyID::OB_PROP_COLOR_HUE_INT)
      .value("OB_PROP_COLOR_POWER_LINE_FREQUENCY_INT",
             OBPropertyID::OB_PROP_COLOR_POWER_LINE_FREQUENCY_INT)
      .value("OB_PROP_DEPTH_AUTO_EXPOSURE_BOOL",
             OBPropertyID::OB_PROP_DEPTH_AUTO_EXPOSURE_BOOL)
      .value("OB_PROP_DEPTH_EXPOSURE_INT",
             OBPropertyID::OB_PROP_DEPTH_EXPOSURE_INT)
      .value("OB_PROP_DEPTH_GAIN_INT", OBPropertyID::OB_PROP_DEPTH_GAIN_INT)
      .value("OB_PROP_IR_AUTO_EXPOSURE_BOOL",
             OBPropertyID::OB_PROP_IR_AUTO_EXPOSURE_BOOL)
      .value("OB_PROP_IR_EXPOSURE_INT", OBPropertyID::OB_PROP_IR_EXPOSURE_INT)
      .value("OB_PROP_IR_GAIN_INT", OBPropertyID::OB_PROP_IR_GAIN_INT)
      .value("OB_PROP_IR_CHANNEL_DATA_SOURCE_INT",
             OBPropertyID::OB_PROP_IR_CHANNEL_DATA_SOURCE_INT)
      .value("OB_PROP_DEPTH_RM_FILTER_BOOL",
             OBPropertyID::OB_PROP_DEPTH_RM_FILTER_BOOL)
      .value("OB_PROP_SDK_DISPARITY_TO_DEPTH_BOOL",
             OBPropertyID::OB_PROP_SDK_DISPARITY_TO_DEPTH_BOOL)
      .value("OB_PROP_SDK_DEPTH_FRAME_UNPACK_BOOL",
             OBPropertyID::OB_PROP_SDK_DEPTH_FRAME_UNPACK_BOOL)
      .value("OB_PROP_SDK_IR_FRAME_UNPACK_BOOL",
             OBPropertyID::OB_PROP_SDK_IR_FRAME_UNPACK_BOOL)
      .value("OB_PROP_SDK_ACCEL_FRAME_TRANSFORMED_BOOL",
             OBPropertyID::OB_PROP_SDK_ACCEL_FRAME_TRANSFORMED_BOOL)
      .value("OB_PROP_SDK_GYRO_FRAME_TRANSFORMED_BOOL",
             OBPropertyID::OB_PROP_SDK_GYRO_FRAME_TRANSFORMED_BOOL)
      .value("OB_PROP_SDK_IR_LEFT_FRAME_UNPACK_BOOL",
             OBPropertyID::OB_PROP_SDK_IR_LEFT_FRAME_UNPACK_BOOL)
      .value("OB_PROP_SDK_IR_RIGHT_FRAME_UNPACK_BOOL",
             OBPropertyID::OB_PROP_SDK_IR_RIGHT_FRAME_UNPACK_BOOL)
      .value("OB_RAW_DATA_CAMERA_CALIB_JSON_FILE",
             OBPropertyID::OB_RAW_DATA_CAMERA_CALIB_JSON_FILE);

  py::enum_<OBPropertyType>(m, "OBPropertyType")
      .value("OB_BOOL_PROPERTY", OBPropertyType::OB_BOOL_PROPERTY)
      .value("OB_INT_PROPERTY", OBPropertyType::OB_INT_PROPERTY)
      .value("OB_FLOAT_PROPERTY", OBPropertyType::OB_FLOAT_PROPERTY)
      .value("OB_STRUCT_PROPERTY", OBPropertyType::OB_STRUCT_PROPERTY);

  py::class_<OBPropertyItem>(m, "OBPropertyItem")
      .def(py::init<>())
      .def_readwrite("id", &OBPropertyItem::id)
      .def_readwrite("name", &OBPropertyItem::name)
      .def_readwrite("type", &OBPropertyItem::type)
      .def_readwrite("permission", &OBPropertyItem::permission);
}
}  // namespace pyorbbecsdk
