from __future__ import annotations

from importlib.metadata import version

from pyorbbecsdk.pyorbbecsdk import (
    AccelFrame,
    AccelStreamProfile,
    AlignFilter,
    CameraParamList,
    ColorFrame,
    ConfidenceFrame,
    Config,
    Context,
    DecimationFilter,
    DepthFrame,
    Device,
    DeviceInfo,
    DeviceList,
    DevicePresetList,
    DisparityTransform,
    EdgeNoiseRemovalFilter,
    Filter,
    FormatConvertFilter,
    Frame,
    FrameSet,
    GyroFrame,
    GyroStreamProfile,
    HDRMergeFilter,
    HoleFillingFilter,
    IRFrame,
    LiDARPointsFrame,
    LiDARStreamProfile,
    LutNoiseRemovalFilter,
    MgcNoiseRemovalFilter,
    NoiseRemovalFilter,
    OBAccelFullScaleRange,
    OBAccelIntrinsic,
)
from pyorbbecsdk.pyorbbecsdk import OBAccelValue
from pyorbbecsdk.pyorbbecsdk import OBAccelValue as OBFloat3D
from pyorbbecsdk.pyorbbecsdk import OBAccelValue as OBGyroValue
from pyorbbecsdk.pyorbbecsdk import (
    OBAlignMode,
    OBBaselineCalibrationParam,
    OBBoolPropertyRange,
    OBCalibrationParam,
    OBCameraDistortion,
    OBCameraDistortionModel,
    OBCameraIntrinsic,
    OBCameraParam,
    OBCmdVersion,
    OBColorPoint,
    OBCommunicationType,
    OBCompressionMode,
    OBCompressionParams,
    OBConvertFormat,
    OBCoordinateSystemType,
    OBDataTranState,
    OBDCPowerState,
    OBDDONoiseRemovalType,
    OBDepthCroppingMode,
    OBDepthPrecisionLevel,
    OBDepthWorkMode,
    OBDepthWorkModeList,
    OBDepthWorkModeTag,
    OBDeviceAccessMode,
    OBDeviceDevelopmentMode,
    OBDeviceIpAddrConfig,
    OBDeviceSyncConfig,
    OBDeviceTemperature,
    OBDeviceTimestampResetConfig,
    OBDeviceType,
    OBEdgeNoiseRemovalFilterParams,
    OBEdgeNoiseRemovalType,
    OBError,
    OBErrorDetails,
    OBException,
    OBExtrinsic,
    OBFileTranState,
    OBFilterConfigSchemaItem,
    OBFilterConfigValueType,
    OBFilterList,
    OBFloatPropertyRange,
    OBFormat,
    OBFrameAggregateOutputMode,
    OBFrameMetadataType,
    OBFrameType,
    OBGvcpPortScheme,
    OBGyroFullScaleRange,
    OBGyroIntrinsic,
)
from pyorbbecsdk.pyorbbecsdk import OBGyroSampleRate
from pyorbbecsdk.pyorbbecsdk import OBGyroSampleRate as OBAccelSampleRate
from pyorbbecsdk.pyorbbecsdk import (
    OBHardwareDecimationConfig,
    OBHdrConfig,
    OBHoleFillingMode,
    OBIntPropertyRange,
    OBIpSourceType,
    OBLiDARPoint,
    OBLiDARScanPoint,
    OBLiDARScanRate,
    OBLiDARSpherePoint,
    OBLogLevel,
    OBLutNoiseRemovalFilterParams,
    OBMediaState,
    OBMediaType,
    OBMgcNoiseRemovalFilterParams,
    OBMultiDeviceSyncConfig,
    OBMultiDeviceSyncMode,
    OBNetIpConfigV2,
    OBNoiseRemovalFilterParams,
    OBPermissionType,
    OBPipelineIssue,
    OBPipelineStatus,
    OBPixelType,
    OBPlaybackStatus,
    OBPoint2f,
    OBPoint3f,
    OBPowerLineFreqMode,
    OBPresetResolutionConfig,
    OBPropertyID,
    OBPropertyItem,
    OBPropertyType,
    OBProtocolVersion,
    OBRect,
    OBRegionOfInterest,
    OBRotateDegreeType,
    OBSensorType,
    OBSequenceIdItem,
    OBSpatialAdvancedFilterParams,
    OBStatus,
    OBStreamType,
    OBSyncMode,
    OBTofExposureThresholdControl,
    OBTofFilterRange,
    OBUint8PropertyRange,
    OBUint16PropertyRange,
    OBUpgradeState,
    OBUSBPowerState,
    Pipeline,
    PlaybackDevice,
    PointCloudFilter,
    PointsFrame,
    PresetResolutionConfigList,
    RecordDevice,
    Sensor,
    SensorList,
    SequenceIdFilter,
    SpatialAdvancedFilter,
    StreamProfile,
    StreamProfileList,
    TemporalFilter,
    ThresholdFilter,
    VideoFrame,
    VideoStreamProfile,
    get_version,
    save_lidar_point_cloud_to_ply,
    save_point_cloud_to_ply,
    transformation2dto2d,
    transformation2dto3d,
    transformation3dto2d,
    transformation3dto3d,
)

from . import pyorbbecsdk

__all__: list[str] = [
    "AccelFrame",
    "AccelStreamProfile",
    "AlignFilter",
    "COUNT",
    "CameraParamList",
    "ColorFrame",
    "ConfidenceFrame",
    "Config",
    "Context",
    "DecimationFilter",
    "DepthFrame",
    "Device",
    "DeviceInfo",
    "DeviceList",
    "DevicePresetList",
    "DisparityTransform",
    "EdgeNoiseRemovalFilter",
    "Filter",
    "FormatConvertFilter",
    "Frame",
    "FrameSet",
    "GyroFrame",
    "GyroStreamProfile",
    "HDRMergeFilter",
    "HoleFillingFilter",
    "IRFrame",
    "LiDARPointsFrame",
    "LiDARStreamProfile",
    "LutNoiseRemovalFilter",
    "MgcNoiseRemovalFilter",
    "NoiseRemovalFilter",
    "OBAccelFullScaleRange",
    "OBAccelIntrinsic",
    "OBAccelSampleRate",
    "OBAccelValue",
    "OBAlignMode",
    "OBBaselineCalibrationParam",
    "OBBoolPropertyRange",
    "OBCalibrationParam",
    "OBCameraDistortion",
    "OBCameraDistortionModel",
    "OBCameraIntrinsic",
    "OBCameraParam",
    "OBCmdVersion",
    "OBColorPoint",
    "OBCommunicationType",
    "OBCompressionMode",
    "OBCompressionParams",
    "OBConvertFormat",
    "OBCoordinateSystemType",
    "OBDCPowerState",
    "OBDDONoiseRemovalType",
    "OBDataTranState",
    "OBDepthCroppingMode",
    "OBDepthPrecisionLevel",
    "OBDepthWorkMode",
    "OBDepthWorkModeList",
    "OBDepthWorkModeTag",
    "OBDeviceAccessMode",
    "OBDeviceDevelopmentMode",
    "OBDeviceIpAddrConfig",
    "OBDeviceSyncConfig",
    "OBDeviceTemperature",
    "OBDeviceTimestampResetConfig",
    "OBDeviceType",
    "OBEdgeNoiseRemovalFilterParams",
    "OBEdgeNoiseRemovalType",
    "OBError",
    "OBErrorDetails",
    "OBException",
    "OBExtrinsic",
    "OBFileTranState",
    "OBFilterConfigSchemaItem",
    "OBFilterConfigValueType",
    "OBFilterList",
    "OBFloat3D",
    "OBFloatPropertyRange",
    "OBFormat",
    "OBFrameAggregateOutputMode",
    "OBFrameMetadataType",
    "OBFrameType",
    "OBGvcpPortScheme",
    "OBGyroFullScaleRange",
    "OBGyroIntrinsic",
    "OBGyroSampleRate",
    "OBGyroValue",
    "OBHardwareDecimationConfig",
    "OBHdrConfig",
    "OBHoleFillingMode",
    "OBIntPropertyRange",
    "OBIpSourceType",
    "OBLiDARPoint",
    "OBLiDARScanPoint",
    "OBLiDARScanRate",
    "OBLiDARSpherePoint",
    "OBLogLevel",
    "OBLutNoiseRemovalFilterParams",
    "OBMediaState",
    "OBMediaType",
    "OBMgcNoiseRemovalFilterParams",
    "OBMultiDeviceSyncConfig",
    "OBMultiDeviceSyncMode",
    "OBNetIpConfigV2",
    "OBNoiseRemovalFilterParams",
    "OBPermissionType",
    "OBPipelineIssue",
    "OBPipelineStatus",
    "OBPixelType",
    "OBPlaybackStatus",
    "OBPoint2f",
    "OBPoint3f",
    "OBPowerLineFreqMode",
    "OBPresetResolutionConfig",
    "OBPropertyID",
    "OBPropertyItem",
    "OBPropertyType",
    "OBProtocolVersion",
    "OBRect",
    "OBRegionOfInterest",
    "OBRotateDegreeType",
    "OBSensorType",
    "OBSequenceIdItem",
    "OBSpatialAdvancedFilterParams",
    "OBStatus",
    "OBStreamType",
    "OBSyncMode",
    "OBTofExposureThresholdControl",
    "OBTofFilterRange",
    "OBUSBPowerState",
    "OBUint16PropertyRange",
    "OBUint8PropertyRange",
    "OBUpgradeState",
    "PAUSED",
    "PLAYING",
    "Pipeline",
    "PlaybackDevice",
    "PointCloudFilter",
    "PointsFrame",
    "PresetResolutionConfigList",
    "RecordDevice",
    "SAMPLE_RATE_100_HZ",
    "SAMPLE_RATE_12_5_HZ",
    "SAMPLE_RATE_16_KHZ",
    "SAMPLE_RATE_1_5625_HZ",
    "SAMPLE_RATE_1_KHZ",
    "SAMPLE_RATE_200_HZ",
    "SAMPLE_RATE_25_HZ",
    "SAMPLE_RATE_2_KHZ",
    "SAMPLE_RATE_32_KHZ",
    "SAMPLE_RATE_3_125_HZ",
    "SAMPLE_RATE_400_HZ",
    "SAMPLE_RATE_4_KHZ",
    "SAMPLE_RATE_500_HZ",
    "SAMPLE_RATE_50_HZ",
    "SAMPLE_RATE_6_25_HZ",
    "SAMPLE_RATE_800_HZ",
    "SAMPLE_RATE_8_KHZ",
    "SAMPLE_RATE_UNKNOWN",
    "STOPPED",
    "Sensor",
    "SensorList",
    "SequenceIdFilter",
    "SpatialAdvancedFilter",
    "StreamProfile",
    "StreamProfileList",
    "TemporalFilter",
    "ThresholdFilter",
    "UNKNOWN",
    "VideoFrame",
    "VideoStreamProfile",
    "get_version",
    "pyorbbecsdk",
    "save_lidar_point_cloud_to_ply",
    "save_point_cloud_to_ply",
    "transformation2dto2d",
    "transformation2dto3d",
    "transformation3dto2d",
    "transformation3dto3d",
    "version",
]
COUNT: OBPlaybackStatus  # value = <OBPlaybackStatus.COUNT: 4>
PAUSED: OBPlaybackStatus  # value = <OBPlaybackStatus.PAUSED: 2>
PLAYING: OBPlaybackStatus  # value = <OBPlaybackStatus.PLAYING: 1>
SAMPLE_RATE_100_HZ: OBGyroSampleRate  # value = <OBGyroSampleRate.SAMPLE_RATE_100_HZ: 7>
SAMPLE_RATE_12_5_HZ: OBGyroSampleRate  # value = <OBGyroSampleRate.SAMPLE_RATE_12_5_HZ: 4>
SAMPLE_RATE_16_KHZ: OBGyroSampleRate  # value = <OBGyroSampleRate.SAMPLE_RATE_16_KHZ: 14>
SAMPLE_RATE_1_5625_HZ: OBGyroSampleRate  # value = <OBGyroSampleRate.SAMPLE_RATE_1_5625_HZ: 1>
SAMPLE_RATE_1_KHZ: OBGyroSampleRate  # value = <OBGyroSampleRate.SAMPLE_RATE_1_KHZ: 10>
SAMPLE_RATE_200_HZ: OBGyroSampleRate  # value = <OBGyroSampleRate.SAMPLE_RATE_200_HZ: 8>
SAMPLE_RATE_25_HZ: OBGyroSampleRate  # value = <OBGyroSampleRate.SAMPLE_RATE_25_HZ: 5>
SAMPLE_RATE_2_KHZ: OBGyroSampleRate  # value = <OBGyroSampleRate.SAMPLE_RATE_2_KHZ: 11>
SAMPLE_RATE_32_KHZ: OBGyroSampleRate  # value = <OBGyroSampleRate.SAMPLE_RATE_32_KHZ: 15>
SAMPLE_RATE_3_125_HZ: OBGyroSampleRate  # value = <OBGyroSampleRate.SAMPLE_RATE_3_125_HZ: 2>
SAMPLE_RATE_400_HZ: OBGyroSampleRate  # value = <OBGyroSampleRate.SAMPLE_RATE_400_HZ: 16>
SAMPLE_RATE_4_KHZ: OBGyroSampleRate  # value = <OBGyroSampleRate.SAMPLE_RATE_4_KHZ: 12>
SAMPLE_RATE_500_HZ: OBGyroSampleRate  # value = <OBGyroSampleRate.SAMPLE_RATE_500_HZ: 9>
SAMPLE_RATE_50_HZ: OBGyroSampleRate  # value = <OBGyroSampleRate.SAMPLE_RATE_50_HZ: 6>
SAMPLE_RATE_6_25_HZ: OBGyroSampleRate  # value = <OBGyroSampleRate.SAMPLE_RATE_6_25_HZ: 3>
SAMPLE_RATE_800_HZ: OBGyroSampleRate  # value = <OBGyroSampleRate.SAMPLE_RATE_800_HZ: 17>
SAMPLE_RATE_8_KHZ: OBGyroSampleRate  # value = <OBGyroSampleRate.SAMPLE_RATE_8_KHZ: 13>
SAMPLE_RATE_UNKNOWN: OBGyroSampleRate  # value = <OBGyroSampleRate.SAMPLE_RATE_UNKNOWN: 0>
STOPPED: OBPlaybackStatus  # value = <OBPlaybackStatus.STOPPED: 3>
UNKNOWN: OBPlaybackStatus  # value = <OBPlaybackStatus.UNKNOWN: 0>
__version__: str = "2.1.0"
